### ISSUE TITLE
Why deprecated?

### ISSUE THREAD

**Issue by inancgumus** [steelbrain/vanilla-jsx#11]

**Comment by steelbrain** [comment]
Deprecated because you can't build anything real with this, you have to build a component abstraction on top of it in every project you work.

**Comment by inancgumus** [comment]
Wow, fast very response. 
It's actually seems like a good idea.

I'm looking for a vanilla jsx that supports react eco system. Like, using matt-esch/virtualdom to use it with natively-React supporting library airbnb/enzyme but without React bolierplates.

These days JS world is so tedious. There are many choices to pick up.

**Comment by steelbrain** [comment]
Try `preact` instead, it's the same size as this and supports full react API

**Comment by inancgumus** [comment]
Yeah, that's on my mind too. What do you think about matt-esch/virtualdom vs preact? Not the same thing although.

**Comment by steelbrain** [comment]
`matt-esch/virtualdom` is IMHO ugly, I personally don't like the codebase and think it has overkills all over the place. I am using `preact` in my projects

**Comment by inancgumus** [comment]
Yeah, it seems like bloated. Will add +1 to `preact` on my list, thanks @steelbrain

**Comment by steelbrain** [comment]
np man, have fun 👍
