### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by mnemanja** [steelbrain/vanilla-jsx#12]
The last release was 2 years ago and the repo looks like it's not used (almost no issues resolved or unresolved), but npm shows different data.
![image](https://user-images.githubusercontent.com/1423218/35910512-0e155a04-0bf7-11e8-9ff3-291543387307.png)

Version is 3, but there are only 2 releases: 3.0.0 and 3.0.1. What's up with this?

Is this repo still maintained?

**Comment by steelbrain** [comment]
@mnemanja If by maintained you mean I'll fix the bugs known, then yes it's maintained :)

Closing as answered but feel free to continue discussing
